export { default as ChatWorkspace } from '@/features/workspace/ai-chat-panel/components/ChatWorkspace';
export { default as TopBar } from './top-bar/TopBar';
export { default as StandardTopBar } from './top-bar/StandardTopBar';
export { useWorkspace } from './hooks/useWorkspace';
export { useWorkspaceStore } from './store/useWorkspaceStore';
export type { ViewState, ActiveTab, Message, ProjectSummary } from './types/index';
export { HomeMainView } from '@/features/home';
export { PremiumTemplatesGallery } from '@/features/workspace/templates';
export { LiveProjectsDashboard } from '@/features/workspace/live-websites';
export { AIChatLandingPage, AIChatInputPanel } from '@/features/workspace/ai-chat-panel';
